# Generated by Django 4.1.7 on 2023-03-09 14:50

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import dpbackend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idkarty', models.CharField(max_length=12)),
                ('nazev', models.CharField(default='beef', max_length=30)),
                ('vlastnik', models.CharField(max_length=30)),
                ('zemdelka', models.DecimalField(decimal_places=6, max_digits=9)),
                ('zemsirka', models.DecimalField(decimal_places=6, max_digits=9)),
                ('putpredmet', models.CharField(default=dpbackend.models.Karta.putovni_predmet_default, max_length=30)),
                ('pocetnalezu', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PutovniPredmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idputpredmetu', models.CharField(max_length=30)),
                ('pozice', models.BooleanField(default=False)),
                ('idpozice', models.CharField(max_length=30)),
                ('vlastnik', models.CharField(max_length=30)),
                ('karty', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='card', max_length=12), blank=True, default=list, size=None)),
                ('cesta', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SberatelskyPredmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsberpredmetu', models.CharField(max_length=30)),
                ('nalezeno', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('otevrenekese', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=dpbackend.models.Hrac.otevrenekese_default, size=None)),
                ('otevrenekesepoc', models.IntegerField(default=0)),
                ('putpredmet', models.CharField(default='', max_length=30)),
                ('putpredmety', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=dpbackend.models.Hrac.putpredmety_default, size=None)),
                ('sberpredmet', models.JSONField(blank=True, default=dpbackend.models.Hrac.sberpredmet_default)),
                ('pocetsberpred', models.IntegerField(default=0)),
                ('vlastnenekese', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), blank=True, default=dpbackend.models.Hrac.vlastnenekese_default, size=None)),
                ('registrace', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
