# Generated by Django 4.1.7 on 2023-03-30 13:21

from django.db import migrations, models
import dpbackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('dpbackend', '0002_karta_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrac',
            name='player_id',
            field=models.CharField(default=dpbackend.models.Hrac.player_id_default, max_length=22),
        ),
    ]
