# Generated by Django 4.1.7 on 2023-03-30 14:38

from django.db import migrations, models
import dpbackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('dpbackend', '0003_hrac_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='putovnipredmet',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to=dpbackend.models.PutovniPredmet.upload_path),
        ),
        migrations.AlterField(
            model_name='putovnipredmet',
            name='cesta',
            field=models.CharField(default=dpbackend.models.PutovniPredmet.upload_path, max_length=100),
        ),
    ]
