# Generated by Django 4.1.7 on 2023-03-30 17:56

from django.db import migrations, models
import dpbackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('dpbackend', '0004_putovnipredmet_obrazek_alter_putovnipredmet_cesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karta',
            name='putpredmet',
            field=models.CharField(default=dpbackend.models.Karta.card_id_default, max_length=30),
        ),
        migrations.AlterField(
            model_name='putovnipredmet',
            name='idputpredmetu',
            field=models.CharField(default=dpbackend.models.PutovniPredmet.putovni_predmet_default, max_length=30),
        ),
    ]
