# Generated by Django 4.1.7 on 2023-03-30 17:57

from django.db import migrations, models
import dpbackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('dpbackend', '0005_alter_karta_putpredmet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karta',
            name='putpredmet',
            field=models.CharField(default=dpbackend.models.Karta.putovni_predmet_default, max_length=30),
        ),
    ]
