# Generated by Django 4.1.7 on 2023-03-30 19:00

from django.db import migrations, models
import dpbackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('dpbackend', '0008_alter_putovnipredmet_cesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrac',
            name='putpredmet',
            field=models.CharField(default=dpbackend.models.Hrac.putovni_predmet_default, max_length=30),
        ),
    ]
