# Generated by Django 4.1.7 on 2023-04-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpbackend', '0009_alter_hrac_putpredmet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SberatelskyPredmet',
        ),
    ]
